name: Yii2 Advanced CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: yii2advanced_test
        ports: [ 3306:3306 ]
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, gd, pdo_mysql, zip
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ignore-platform-reqs

      - name: Prepare environment
        run: |
          cp .github/.env.test .env
          php init --env=Development --overwrite=All
          mkdir -p backend/runtime frontend/runtime console/runtime
          chmod -R 777 backend/runtime frontend/runtime console/runtime

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            mysql -h 127.0.0.1 -u root -e "SELECT 1" && break || sleep 5
          done
          mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS yii2advanced_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"

      - name: Run migrations
        run: php yii migrate --interactive=0

      - name: Run Codeception tests
        run: |
          vendor/bin/codecept build
          vendor/bin/codecept run unit
